name: build

on: ["push", "pull_request"]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: npm install, npm test
        run: |
          npm install
          npm test
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
